#!/bin/bash

DOTNET="$(which dotnet)"
CONFIGURATION=$1
MONO=$2
NETCORE=$3
PARAMETERS="build -c ${CONFIGURATION} --no-dependencies"
SRC_FRAME=""
TEST_FRAME=""

if [[ ("$MONO" == "true") && ("$NETCORE" == "false") ]]; then
	SRC_FRAME="-f net451"
    TEST_FRAME="-f net451"
elif [[ ("$NETCORE" == "true") && ("$MONO" == "false") ]]; then
	SRC_FRAME="-f netstandard1.6"
	TEST_FRAME="-f netcoreapp1.0"
fi

$DOTNET $PARAMETERS $SRC_FRAME src/Localization.AspNetCore.TagHelpers/project.json
ret_code=$?
if [ "$ret_code" != "0" ]; then
	exit $ret_code
fi

if [[ ("$NETCORE" == "true") ]]; then
	$DOTNET $PARAMETERS $TEST_FRAME src/Localization.Demo/project.json
	$NPM_EXEC="$(which npm 2>/dev/null)"
	if [ "$NPM_EXEC" ]; then
		pushd src/Localization.Demo
		$NPM_EXEC restore
		$NPM_EXEC bower restore
		$NPM_EXEC gulp build
		popd
	fi
fi

$DOTNET $PARAMETERS $TEST_FRAME test/Localization.AspNetCore.TagHelpers.Tests/project.json
ret_code=$?
exit $ret_code
